baseURL = 'https://nvimer.org/'
languageCode = 'en-us'
title = "Jin's blog"
# setting theme
theme = 'paper'

# config for menu
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/About/"
    weight = 10
  [[menu.main]]
    identifier = "ArchInstall"
    name = "ArchInstall"
    url = "/ArchInstall/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

#  config for paper
[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  github = 'jinzhongjia'                 
  rss = true                                

  # home page profile
  avatar = 'mail@nvimer.org'                 # gravatar email or image url
  name = 'jinzhongjia'

  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'https://cdn.v2ex.com/gravatar/'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = true                               # enable KaTeX math typesetting globally

